### PR TITLE
Remove the tests from the include on build

### PR DESCRIPTION
**Pull request by danthegoodman1**
Great agony and suffering occurred ends now. This solves the path issue because the tests were getting copied and built so there was the extra `src/` and `test/` layer in the `/build/` folder

Change-type: patch

### CODE REVIEW

**Comment by Hades32** [comment]
@balena-ci I self-certify!

**Review by Hades32 — APPROVED** [review]

**Comment by danthegoodman1** [comment]
@balena-ci I self-certify!

**Comment by danthegoodman1** [comment]
that was force of habit lol

**Comment by danthegoodman1** [comment]
this is wacked

**Pull request closed without merging**
